### ISSUE TITLE
[Bug]: Media Cleaner stopped working 5-8 weeks ago

### ISSUE THREAD

**Issue by MagnusL3D-code** [shemanaev/jellyfin-plugin-media-cleaner#15]
### What happened?

Up until 5-8 weeks ago Media Cleaner worked perfectly. Since then it has not been deleting media however.

I am getting this in the log:
```
[2023-02-23 09:14:04.891 +00:00] [INF] [90] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "Played media cleanup"
[2023-02-23 09:14:04.924 +00:00] [INF] [90] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "MediaCleanupTask"
[2023-02-23 09:14:04.924 +00:00] [INF] [89] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Played media cleanup"
[2023-02-23 09:14:05.301 +00:00] [ERR] [89] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Library.UserDataManager.GetUserData(User user, BaseItem item)
   at MediaCleaner.Filtering.FavoritesFilter.IsFavorite(User user, BaseItem item)
   at MediaCleaner.Filtering.FavoritesFilter.<>c__DisplayClass7_0.<Apply>b__0(User m)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaCleaner.Filtering.FavoritesFilter.Apply(List`1 items)
   at MediaCleaner.JunkCollectors.BaseJunkCollector.Execute(List`1 users, IEnumerable`1 filters, CancellationToken cancellationToken)
   at MediaCleaner.MediaCleanupTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2023-02-23 09:14:05.603 +00:00] [INF] [89] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Played media cleanup" Failed after 0 minute(s) and 0 second
```

**Comment by MagnusL3D-code** [comment]
I am not sure I know enough how to do that, running Jellyfin on a NAS through Docker :/

**Comment by shemanaev** [comment]
No worries, let's walk through this. You know where Jellyfin data located since you configured it in Docker? Like where you mounted `/config`. You go into that directory, then `plugins`, find `Media Cleaner_2.6.0.0` and replace with files from archive.

**Comment by MagnusL3D-code** [comment]
Allright, stopped the docker, copied the files over, and started the docker. Not sure what to do now, because I don't know how make it force run.

**Comment by shemanaev** [comment]
Go to admin dashboard in Jellyfin, then Scheduled Tasks, find Played media cleanup and run it.

**Comment by MagnusL3D-code** [comment]
Aha thanks for your patience with me ! =) Doesnt look good though.
![image](https://user-images.githubusercontent.com/53098922/220981617-18490a35-755d-4565-b514-9638d67bc0b3.png)

**Comment by MagnusL3D-code** [comment]
I would be it says: 
![image](https://user-images.githubusercontent.com/53098922/220983142-dcdf0299-7788-48e9-bcfe-1488b62fccad.png)

**Comment by shemanaev** [comment]
Oh, unfortunate...

**Comment by MagnusL3D-code** [comment]
is there anyway to rollback to 2.5.2.0 ? i see i have that and several earlier versions in my plugins folder

**Comment by shemanaev** [comment]
Let's try [this build](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/suites/11165578903/artifacts/570103461) then.

**Comment by shemanaev** [comment]
>is there anyway to rollback to 2.5.2.0 

Yes, you should be able to do it from plugins Catalog. There you can select specific version.
But it will not solve your problem :)

**Comment by MagnusL3D-code** [comment]
Allright tried the new zip and it still failed and error no troubleshooting error log :/

**Comment by shemanaev** [comment]
Ok, let's try to narrow down the possible errors. Could you set -1 to "Keep for" for Movies, Series and Videos in plugin settings one by one and check if there will be error for each section?

**Comment by MagnusL3D-code** [comment]
I already have all except Series on -1

**Comment by shemanaev** [comment]
> I already have all except Series on -1

It's already helpful.
Let's repeat our testing with [new build](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/suites/11166051150/artifacts/570137856)

**Comment by MagnusL3D-code** [comment]
It did run and it did remove several files. There is one it missed but I miiight have fiddled with that a bit much during testing so maybe I messed something up with it. AND!! The Troubleshooting log works!
![image](https://user-images.githubusercontent.com/53098922/220991555-e9c203e9-88a6-4a1a-bda7-7c3ef3e73b4d.png)

**Comment by shemanaev** [comment]
Nice. Thanks for debugging this case with me.
No further actions required from you, plugin updates will be received as usual.
If you'll encounter this issue again, feel free to reopen.

**Comment by MagnusL3D-code** [comment]
Allright ! thanks for all the help, so happy it works again ! =)

**Comment by MagnusL3D-code** [comment]
Just as a follow up, the one that didnt work, it appears I had favorited that show while trying to figure all this out. After removing favorite it got cleaned up correctly!
