### ISSUE TITLE
[Bug]: Failure with 10.9 (unstable)

### ISSUE THREAD

**Issue by ScottESanDiego** [shemanaev/jellyfin-plugin-media-cleaner#46]
### What happened?

This plugin is a life-saver, and given that Jellyfin 10.9 is now in feature-freeze I thought I'd give it a try and provide feedback.  Unfortunately, the media-cleaner plugin installs but fails to run:

```[2024-03-22 21:33:35.606 +00:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: "TaskCleanCollectionsAndPlaylists" Completed after 0 minute(s) and 0 seconds
[2024-03-22 21:33:36.713 +00:00] [INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2024-03-22 21:34:28.605 +00:00] [ERR] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.Collections.Generic.IReadOnlyList`1<System.ValueTuple`2<System.String,Jellyfin.Data.Enums.SortOrder>>)'.
   at MediaCleaner.ItemsAdapter.GetUserItems(BaseItemKind kind, User user, String sortBy)
   at MediaCleaner.ItemsAdapter.GetPlayedItems(BaseItemKind kind, User user, CancellationToken cancellationToken)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at MediaCleaner.JunkCollectors.BaseJunkCollector.Execute(List`1 users, IEnumerable`1 filters, CancellationToken cancellationToken)
   at MediaCleaner.MediaCleanupTask.CollectMovies(List`1 users, List`1 usersWithFavorites, ItemsAdapter itemsAdapter, CancellationToken cancellationToken)
   at MediaCleaner.MediaCleanupTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-03-22 21:34:28.606 +00:00] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Played media cleanup" Failed after 0 minute(s) and 0 seconds```

### Troubleshooting info

_No response_

**Comment by Yankees4life** [comment]
Have the same error on stable. I guess I'm gonna have to back to manually deleting files in the interim

**Comment by David-Moreira** [comment]
Also wondering about this. v10.9 has just released and it'd be nice to have this plugin be compatible.

**Comment by shemanaev** [comment]
There are big breaking changes in UI department. It will take some time to fix.

**Comment by shemanaev** [comment]
New version for 10.9 released
