### ISSUE TITLE
[Bug]: Unable to run shudle task

### ISSUE THREAD

**Issue by BreizhHardware** [shemanaev/jellyfin-plugin-media-cleaner#55]
### What happened?

I want to manually run my media cleaner schudled task but I encounter this error message:

`[18:50:28] [ERR] [34] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task

System.NullReferenceException: Object reference not set to an instance of an object.

   at MediaCleaner.Filtering.SeriesFilter.Apply(List`1 items)

   at MediaCleaner.JunkCollectors.BaseJunkCollector.ExecuteNotPlayed(List`1 users, IEnumerable`1 filters, CancellationToken cancellationToken)

   at MediaCleaner.MediaCleanupTask.CollectNotPlayedSeries(List`1 users, List`1 usersWithFavorites, ItemsAdapter itemsAdapter, CancellationToken cancellationToken)

   at MediaCleaner.MediaCleanupTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)

   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)

[18:50:28] [INF] [34] Emby.Server.Implementations.ScheduledTasks.TaskManager: Played media cleanup Failed after 0 minute(s) and 19 seconds`

Here is my settings :

![image](https://github.com/user-attachments/assets/27c36b92-5c66-4736-ba92-4b8260b483e0)

I use a dockerized jellyfin

**Comment by shemanaev** [comment]
Hi!
It's hard to tell what's going on. 
We could start with [enabling Debug logging](https://jellyfin.org/docs/general/administration/troubleshooting/#debug-logging) ("Trace" level will be excellent) and heading to Troubleshooting section of plugin then. There should be a lot of data in Jellyfin's log file then, that can give me some clues.

**Comment by BreizhHardware** [comment]
When I try to display the troubleshooting section I have an error

![image](https://github.com/user-attachments/assets/88893276-5ecc-4926-8007-534480868c21)

**Comment by shemanaev** [comment]
Yes, right. That's why I asked to enable a debug log and see what's going on in Jellyfin's own logs (Dashboard -> Logs section).

**Comment by BreizhHardware** [comment]
So here is the log file, if you need anything else I'm available

[log_20240824.log](https://github.com/user-attachments/files/16738017/log_20240824.log)

**Comment by shemanaev** [comment]
Could you try [this build](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/actions/runs/10546411247/artifacts/1851642490)? Just replace dll and restart Jellyfin.

**Comment by shemanaev** [comment]
Still can't locate it. Let's another shot with [new build](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/actions/runs/10564903444/artifacts/1855857493). Remember to go to Troubleshooting section after plugin update and then download log.

**Comment by BreizhHardware** [comment]
After the last Jellyfin update (10.9.10) my issue is fixed, thank you for your time
